# Generated by Django 2.0.4 on 2018-05-07 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostic_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='has_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_details', models.TextField(default=None)),
                ('price', models.IntegerField()),
                ('delivary_in', models.IntegerField()),
                ('is_home_deliverable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Clinic', 'Clinic'), ('Medical college', 'Medical college'), ('Diagnostic center', 'Diagnostic center'), ('Hospital', 'Hospital'), ('Check up center', 'Check up center')], default='Hospital', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=20)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Barishal', 'Barishal'), ('Dinajput', 'Dinajput'), ('Chittagong', 'Chittagong'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur')], max_length=50)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('price', models.IntegerField()),
                ('delivary_in', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='package_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.package')),
                ('test', models.ManyToManyField(to='medical.diagnostic_test')),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('Bad', 'Bad'), ('Average', 'Average'), ('Good', 'Good'), ('Best', 'Best'), ('Excellent', 'Excellent')], max_length=15)),
                ('comments', models.TextField()),
                ('proof', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('aprove', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.has_test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='test_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='has_test',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.hospital'),
        ),
        migrations.AddField(
            model_name='has_test',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.diagnostic_test'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.hospital'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='diagnostic_test',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.test_category'),
        ),
    ]
